<?php

/**
 * Implements hook_theme()
 */

function tweets_theme($existing, $type, $theme, $path) {
  return [
    'tweets' => [
      'variables' => [
        'tweets' => NULL,
      ],
    ],

  ];
}

function template_preprocess_tweets(&$variables) {
  $variables['attributes']['class'][] = 'tweets';
  $tweets = $variables['tweets'];
  $items = array();
  if (!empty($tweets)) {
    foreach ($tweets as $tweet) {

      $settings = array(
        '#type' => 'processed_text',
        '#text' => $tweet->text,
        '#format' => NULL,
        '#filter_types_to_skip' => array(),
        '#langcode' => '',
      );
      $text = \Drupal::service('renderer')->renderPlain($settings);

        $user_url = 'https://twitter.com/';
        if (!is_null($tweet->user->screen_name))
            $user_url.= $tweet->user->screen_name;
        if (!is_null($tweet->id_str))
            $user_url .= '/status/' . $tweet->id_str;

      $items[] = array(
        'id' => $tweet->id,
        'text' => $text,
        'time' => $tweet->created_at,
        'time_ago' => \Drupal::service('date.formatter')
          ->formatInterval(REQUEST_TIME - strtotime($tweet->created_at)),
        'date' =>  \Drupal::service('date.formatter')
          ->format(strtotime($tweet->created_at), 'custom', 'd.m.y - h:m'),
        'date_us' =>  \Drupal::service('date.formatter')
          ->format(strtotime($tweet->created_at), 'custom', 'm/d/y - h:m'),
        'username' => $tweet->user->screen_name,
        'screen_name' => $tweet->user->screen_name,
        'user_url' => $user_url,
      );
    }
  }
  $variables['items'] = $items;
}
